import type { Listing } from "./types.js";

export const seedListings: Listing[] = [
  {
    id: 1,
    title: "Cut Through the Noise",
    artist: "@inkstations",
    price: 120,
    status: "Available",
    medium: "Screen Print",
    dimensions: "18 x 24 in",
    neighborhood: "East Williamsburg",
    borough: "Brooklyn",
    distance: 0.3,
    story:
      "A hand-pulled three-color print exploring signal, static, and the flyers that survive under fresh paste.",
    image: "/artwork/artwork-01.webp",
    saved: false,
    accent: "red",
    size: "tall",
  },
  {
    id: 2,
    title: "Blue Horizon",
    artist: "@goodclay.nyc",
    price: 180,
    status: "Available",
    medium: "Ceramic",
    dimensions: "5 x 4 in",
    neighborhood: "Ridgewood",
    borough: "Queens",
    distance: 0.8,
    story:
      "Wheel-thrown stoneware with cobalt glaze drips, fired in a small shared studio near the train line.",
    image: "/artwork/artwork-02.webp",
    saved: true,
    accent: "blue",
    size: "standard",
  },
  {
    id: 3,
    title: "Day Shift",
    artist: "@madebycleo",
    price: 450,
    status: "Available",
    medium: "Acrylic",
    dimensions: "20 x 20 in",
    neighborhood: "Bushwick",
    borough: "Brooklyn",
    distance: 0.6,
    story:
      "Layered acrylic and scraped pigment from a studio series about work schedules and borrowed daylight.",
    image: "/artwork/artwork-03.webp",
    saved: false,
    accent: "teal",
    size: "wide",
  },
  {
    id: 4,
    title: "Sunday Sketch",
    artist: "@linebyjules",
    price: 95,
    status: "Available",
    medium: "Ink",
    dimensions: "11 x 14 in",
    neighborhood: "Greenpoint",
    borough: "Brooklyn",
    distance: 1.7,
    story:
      "Loose ink study on heavy paper, made from memory after a morning walk through warehouse blocks.",
    image: "/artwork/artwork-04.webp",
    saved: false,
    accent: "yellow",
    size: "standard",
  },
  {
    id: 5,
    title: "Future Is Us",
    artist: "@print.archive",
    price: 75,
    status: "Available",
    medium: "Risograph",
    dimensions: "12 x 18 in",
    neighborhood: "Bedford-Stuyvesant",
    borough: "Brooklyn",
    distance: 1.1,
    story:
      "Risograph experiment with overprinted color fields and soft registration shifts on recycled stock.",
    image: "/artwork/artwork-05.webp",
    saved: true,
    accent: "magenta",
    size: "tall",
  },
  {
    id: 6,
    title: "Signal Quilt",
    artist: "@threadsignal",
    price: 260,
    status: "Pending",
    medium: "Textile",
    dimensions: "16 x 16 in",
    neighborhood: "Crown Heights",
    borough: "Brooklyn",
    distance: 1.4,
    story:
      "Small fiber piece using stitched blocks, found yarn, and a color rhythm borrowed from corner-store signs.",
    image: "/artwork/artwork-06.webp",
    saved: false,
    accent: "green",
    size: "standard",
  },
  {
    id: 7,
    title: "Paper Memory",
    artist: "@collagedotcom",
    price: 260,
    status: "Pending",
    medium: "Mixed Media",
    dimensions: "14 x 18 in",
    neighborhood: "Crown Heights",
    borough: "Brooklyn",
    distance: 1.4,
    story:
      "Collage of torn pulp, ink transfer, and acrylic wash from a series about saved receipts and lost venues.",
    image: "/artwork/artwork-07.webp",
    saved: false,
    accent: "red",
    size: "wide",
  },
  {
    id: 8,
    title: "Block Study No. 4",
    artist: "@northwall",
    price: 140,
    status: "Sold",
    medium: "Photo Print",
    dimensions: "10 x 10 in",
    neighborhood: "Williamsburg",
    borough: "Brooklyn",
    distance: 0.9,
    story:
      "A graphic street-photo abstraction printed on matte paper, documenting painted walls before renovation.",
    image: "/artwork/artwork-08.webp",
    saved: false,
    accent: "blue",
    size: "standard",
  },
];
